trigger:
  - '*'
  
variables:
    buildConfiguration: 'Release'
    dotnetSdkVersion: '3.1.300'
      
stages:
      - stage: 'Build'
        displayName: 'Build the web application'
        variables:     
          wwwrootDir: 'Tailspin.SpaceGame.Web/wwwroot'
          dotnetSdkVersion: '3.1.300'
        jobs:
          - job: 'build' 
            displayName: 'Job Build web App'
            pool:        
              vmImage: 'ubuntu-18.04'
              demands:
                - npm
            steps:
            - task: UseDotNet@2
              displayName: 'Use .NET Core SDK $(dotnetSdkVersion)'
              inputs:
                 version: '$(dotnetSdkVersion)'
    
            - task: Npm@1
              displayName: 'Run npm install'
              inputs:
                 verbose: false
    
            - script: './node_modules/.bin/node-sass $(wwwrootDir) --output $(wwwrootDir)'
              displayName: 'Compile Sass assets'
    
            - task: gulp@1
              displayName: 'Run gulp tasks'
    
            - script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
              displayName: 'Write build info'
              workingDirectory: $(wwwrootDir)
    
            - task: DotNetCoreCLI@2
              displayName: 'Restore project dependencies'
              inputs:
                  command: 'restore'
                  projects: '**/*.csproj'
    
            - task: DotNetCoreCLI@2
              displayName: 'Build the project - $(buildConfiguration)'
              inputs:
                 command: 'build'
                 arguments: '--no-restore --configuration $(buildConfiguration)'
                 projects: '**/*.csproj'
    
            - task: DotNetCoreCLI@2
              displayName: 'Publish the project - $(buildConfiguration)'
              inputs:
                 command: 'publish'
                 projects: '$(System.DefaultWorkingDirectory)/**/Tailspin.SpaceGame.Web.csproj' # '**/*.csproj'
                 publishWebProjects: false
                 arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
                 zipAfterPublish: true
    
            - publish: '$(Build.ArtifactStagingDirectory)'
              artifact: drop
             
      - stage: 'Dev'
        displayName: 'Deploy DEV web application'
        dependsOn: Build       
        #   condition: and (succeeded() , eq(variables['Build.SourceBranchName'],variables['releaseBranchName']) )
        jobs:
          - job: Provisionning
            displayName: 'Provision infra' 
            variables: 
              - group: Release
            pool:
              vmImage: 'ubuntu-latest'                       
            steps:
             - script: |
                # Exit when any commands returns a failure status
                 set -e 

                # create and write terraform.tvars  
                 echo 'resource_group_location = "'$(ResourceGroupLocation)'"' | tee terraform.tfvars
              
                 # create and write backend.tfvars
                 echo 'resource_group_name = "tf-storage-rg"' | tee backend.tfvars
                 echo 'storage_account_name = "'$(StorageAccountName)'"' | tee -a backend.tfvars
                 echo 'container_name = "tfstate"' | tee -a backend.tfvars
                 echo 'key = "dev.terraform.tfstate"' | tee -a backend.tfvars

                 # terraform init
                   terraform init -input=false -backend-config="backend.tfvars"
                
                 # terraform apply with auto approve
                   terraform apply -input=false -auto-approve

                 # terraform retrieve output  and set pipeline variable
                   WebAppNameDev=$(terraform output appservice_name_dev) 
                   echo "##vso[task.setvariable variable=WebAppNameDev;isOutput=true]$WebAppNameDev"
               name: 'RunTerraform'
               displayName: 'Run Terraform'
               env:
                ARM_CLIENT_ID: $(ARM_CLIENT_ID)
                ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
                ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
                ARM_TENANT_ID: $(ARM_TENANT_ID)

          - deployment: DeployWeb
            displayName: 'Deployment of Space Game web application'
            dependsOn: Provisionning
            pool:
              vmImage: 'Ubuntu-18.04'
            environment: 'dev'
            variables:
              WebAppNameDev: $[dependencies.Provisionning.outputs['RunTerraform.WebAppNameDev']]
            strategy:
             runOnce:
               deploy:
                 steps:
                   - download: current
                     artifact: drop
                   - task: AzureWebApp@1
                     displayName: 'Azure App Service Deploy : WebSite' 
                     inputs:
                       appType: webAppLinux
                       azureSubscription: 'tf-service-connection'
                       appName: '$(WebAppNameDEV)'
                       package: '$(Pipeline.Workspace)/drop/$(buildconfiguration)/*.zip'
      
    
  